# SpectralWoW does not currently accept donations or funding
# We are a community-driven project focused on providing a free gaming experience

# All funding options are disabled as we do not accept payments at this time
# github: 
# patreon: 
# open_collective: 
# ko_fi: 
# tidelift: 
# community_bridge: 
# liberapay: 
# issuehunt: 
# otechie: 
# lfx_crowdfunding: 
# custom: []