name: 🐛 Bug Report
description: Report a bug or issue with SpectralWoW
title: "[BUG] "
labels: ["bug", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        # 🐛 SpectralWoW Bug Report
        
        Thank you for taking the time to report a bug! Please fill out this form as completely as possible to help us understand and fix the issue.
        
        **Before submitting:**
        - Search existing issues to avoid duplicates
        - Make sure you're using the latest version
        - Check our documentation and FAQ
        
        ---

  - type: textarea
    id: bug-description
    attributes:
      label: 🔍 Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug in detail...
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: 🔄 Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: ✅ Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What should have happened instead?
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: ❌ Actual Behavior
      description: A clear and concise description of what actually happened.
      placeholder: What actually happened?
    validations:
      required: true

  - type: dropdown
    id: bug-category
    attributes:
      label: 📂 Bug Category
      description: What category does this bug fall into?
      options:
        - Server Core
        - Database
        - Modules/Scripts
        - Configuration
        - Performance
        - Security
        - Documentation
        - Build/Compilation
        - Spectral Features
        - Player Experience
        - Admin Tools
        - Other
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: 🚨 Severity
      description: How severe is this bug?
      options:
        - Critical (Server crash, data loss)
        - High (Major functionality broken)
        - Medium (Feature partially broken)
        - Low (Minor issue, workaround available)
        - Cosmetic (UI/display issue)
    validations:
      required: true

  - type: dropdown
    id: frequency
    attributes:
      label: 🔁 Frequency
      description: How often does this bug occur?
      options:
        - Always (100%)
        - Often (75%+)
        - Sometimes (25-75%)
        - Rarely (<25%)
        - Once
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: 🖥️ Environment
      description: Information about your environment
      placeholder: |
        - OS: [e.g. Windows 11, Ubuntu 22.04]
        - Compiler: [e.g. MSVC 2022, GCC 11]
        - Database: [e.g. MySQL 8.0, MariaDB 10.6]
        - Server Version: [e.g. SpectralWoW 1.0.0]
        - Commit Hash: [if known]
        - Custom Modules: [list any custom modules]
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: 📋 Logs and Error Messages
      description: Relevant logs, error messages, or stack traces
      placeholder: |
        Paste relevant logs here...
        
        Server logs:
        ```
        [ERROR] ...
        ```
        
        Database logs:
        ```
        [ERROR] ...
        ```
      render: shell

  - type: textarea
    id: screenshots
    attributes:
      label: 📸 Screenshots/Videos
      description: If applicable, add screenshots or videos to help explain the problem
      placeholder: Drag and drop images/videos here or paste links...

  - type: textarea
    id: additional-context
    attributes:
      label: 📝 Additional Context
      description: Any other context about the problem
      placeholder: |
        - When did this start happening?
        - Does this affect all players or specific ones?
        - Any recent changes to the server?
        - Workarounds you've tried?
        - Related issues or discussions?

  - type: checkboxes
    id: checklist
    attributes:
      label: ✅ Pre-Submission Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues for duplicates
          required: true
        - label: I have provided all required information
          required: true
        - label: I have tested this on the latest version
          required: true
        - label: I have included relevant logs and error messages
          required: false
        - label: I have provided steps to reproduce the issue
          required: true

  - type: markdown
    attributes:
      value: |
        ---
        
        **Thank you for helping improve SpectralWoW! 🌟**
        
        Our team will review your bug report and respond as soon as possible. For urgent issues, please contact us on Discord.
        
        *Where legends don't die... they become Spectral*